# 配置文件不能放在根目录下面，否则会被 api 的 application-dev.yml 覆盖
spring:
  h2:
    enabled:
      true console:
  datasource:
#    username: sa
#    password: sa
#    url: jdbc:h2:tcp://localhost/~/survey
#    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/surveyking?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false
  global-config:
    db-config:
      logic-delete-field: deleted